# Generated by Django 4.2.7 on 2023-11-04 22:35

from django.db import migrations, models
import django.db.models.deletion

def populate_iso_code_in_language(apps, schema_editor):
    Language = apps.get_model('book', 'Language')

    print("Update language")
    if Language.objects.exists():
        # for language in Language.object.all():
        Language.objects.filter(name="English").update(iso_code="eng")

def populate_language_iso(apps, schema_editor):
    Language = apps.get_model('book', 'Language')

    Book = apps.get_model('book', 'Book')

    for book in Book.objects.all():
        language_id = book.language_id

        if language_id and Language.objects.filter(id=language_id).exists():
            language = Language.objects.get(id=language_id)
            book.language_iso = language.iso_code
            book.save()

def add_fk_value(apps, schema_editor):
    Language = apps.get_model('book', 'Language')

    Book = apps.get_model('book', 'Book')

    for book in Book.objects.all():
        book_language_code = book.language_iso

        language = Language.objects.get(iso_code=book_language_code)
        book.language = language
        book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        # 1. add charfield in Language
        migrations.AddField(
            model_name='language',
            name='iso_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        # 2. RunPython to insert language_iso_code
        migrations.RunPython(populate_iso_code_in_language),

        # 3. add Charfield 'language_iso' in Book that has FK to Language
        migrations.AddField(
            model_name='book',
            name='language_iso',
            field=models.CharField(max_length=6, null=True),
        ),
        # 4. FK fields to the Language should have attributes null=True
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.language'),
        ),

         # 5. RunPython to 'populate_language_iso' in other models 
        migrations.RunPython(populate_language_iso),

        # 6. Drop FK column
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        # 7. Change Pk in language
        migrations.RemoveField(
            model_name='language',
            name='id',
        ),
        migrations.AlterField(
            model_name='language',
            name='iso_code',
            field=models.CharField(default=None, max_length=6, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        # 8. Add back FK column
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.language'),
        ),

        #. 9. RunPython to insert the value
        migrations.RunPython(add_fk_value),

        # 10. Drop the charfield
        migrations.RemoveField(
            model_name='book',
            name='language_iso',
        ),
    ]
